### ISSUE TITLE
failed to parse S_SPAWN_USER<13> ( i have def 13 in protocol )

### ISSUE THREAD

**Issue by Owyn** [teralove/party-death-markers#4]
```` ERROR tera-proxy-game: [dispatch] handle: failed to parse S_SPAWN_USER<13>
hook: (anonymous) in party-death-markers-master
data: fb01045c000000000000000083019501970199012000b901bb014000f5010000eed12300e120f501008000001bab0bc76b4a074746c43245aaea010000007f27000000003400c30000000000010165180d00080b04007b410100014500000245000003450000000000000000000000000000010000000000000004000000cc0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002f000000000000000000000001f6db0300000000000000000085d4030015650100000000000000803f0000000000000000000000000000000000000000000000000000000000000000000000000000803f0000000000000000000000000000000000000000000000000000000000000000000000000000803f000000000000000000000000000000000000000000000000000000000000000000000000003f19af19000000000000000000010000000000000000640000000000803f500061006e007a006500720069006b000000000000000c0b10021710090f13101000100c100008100c0c10150c101010100c12100f1000000113101313101313130f0f0f0f0f0f0f10130a000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
error: reader[type] is not a function
    at parseField (\Tera-Proxy\node_modules\tera-data-parser\lib\protocol\index.js:366:37)
    at TeraProtocol.parse (\Tera-Proxy\node_modules\tera-data-parser\lib\protocol\index.js:375:7)````

**Comment by teralove** [comment]
what version of proxy are you using? i'm unable to reproduce this error. I'll keep my eyes open

**Comment by Owyn** [comment]
after updating whole proxy folder with new one this error was resolved somehow
